name: JSON Lint
on: [pull_request]
jobs:
  json-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up prereqs
        run: sudo apt install jq
      - name: Lint the json
        run: cat commands.json | jq
